logging:
  level: INFO
  loggers:
    Sadje: DEBUG

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: gregor
    # the password
    password: kitara99
    # the JDBC URL; the database is called banane
    url: jdbc:mysql://localhost:3306/banane